### ISSUE TITLE
Docker container keeps restarting

### ISSUE THREAD

**Issue by chabapj** [BigThunderSR/adt-pulse-mqtt#192]
docker container keeps restarting every 7-8 seconds. The log shows the following:

```
/usr/src/app/adt-pulse.js:242
						var newsat = body.match(/sat=([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/)[1];
						                                                                                             ^

TypeError: Cannot read properties of null (reading '1')
    at Request._callback (/usr/src/app/adt-pulse.js:242:100)
    at self.callback (/usr/src/app/node_modules/request/request.js:185:22)
    at Request.emit (node:events:517:28)
    at Request.<anonymous> (/usr/src/app/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:517:28)
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:631:28)
    at IncomingMessage.emit (node:events:529:35)
    at endReadableNT (node:internal/streams/readable:1400:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Node.js v18.20.1

```
Any ideas? It was working fine for many months until recently.

**Comment by chabapj** [comment]
That was it. The ADT gateway was stuck or down. I have reset it, and it is working flawlessly now. Thank you!
